name: Weather-App-Ci

on: push
    

jobs:
  CI-Weathr:

    runs-on: ubuntu-latest

    
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
           python-version: '3.9'


           
      - name: Linting
        run: |
            python -m venv .venv
            source .venv/bin/activate
            pip install flake8
            flake8 weather/main.py

    
      
      - name: Testing
        run: |
            python -m venv .venv
            source .venv/bin/activate
            pip install -r weather/requirements.txt
            python -m unittest discover weather


  
  CI-UI:

    runs-on: ubuntu-latest

    
    
    steps:
      - uses: actions/checkout@v3

      - name: Install Trivy 
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.52.1/trivy_0.52.1_Linux-64bit.tar.gz
          tar -xzf trivy_0.52.1_Linux-64bit.tar.gz

      - name: Scan code  with trivy
        run: |
            ./trivy fs ./UI

  CI-AUTH:
     runs-on: ubuntu-latest
     steps:
         - uses: actions/checkout@v3

         - name: Set up Go
           uses: actions/setup-go@v4
           with:
             go-version: '1.20'
           

         - name: Scan Cod 
           run: go vet ./auth/authdb/authdb.go

         - name: Install golangci-lint
           run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

         - name: Linting Auth 
           run: golangci-lint run  ./auth/authdb 
        
        
